# Generated by Django 5.2.6 on 2025-09-30 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_wavequestion_unique_together_and_more'),
        ('waves', '0002_wave_legacy_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaveQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('wave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waves.wave')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('wave', 'question'), name='unique_wave_question')],
            },
        ),
    ]
