# Generated by Django 5.2.6 on 2025-10-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_questionscreenshot'),
        ('waves', '0003_wavequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='wavequestion',
            name='screenshots',
            field=models.ManyToManyField(blank=True, related_name='wavequestions', to='questions.questionscreenshot'),
        ),
    ]
