# Generated by Django 5.2.6 on 2025-10-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0004_wavequestion_screenshots'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wave',
            old_name='name',
            new_name='cycle',
        ),
        migrations.AddField(
            model_name='wave',
            name='instrument',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wave',
            name='surveyyear',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
