# Generated by Django 5.2.6 on 2025-10-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0005_rename_name_wave_cycle_wave_instrument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wave',
            name='cycle',
            field=models.CharField(max_length=200),
        ),
    ]
