# Generated by Django 5.2.6 on 2025-10-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0006_alter_wave_cycle'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wavequestion',
            name='unique_wave_question',
        ),
        migrations.RemoveField(
            model_name='wavequestion',
            name='screenshots',
        ),
    ]
