# Generated by Django 5.2.6 on 2025-10-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0007_remove_wavequestion_unique_wave_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wavequestion',
            name='legacy_screenshot_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
