# Generated by Django 5.2.7 on 2025-12-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0008_wavequestion_legacy_screenshot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wave',
            name='surveyyear',
            field=models.CharField(max_length=10),
        ),
    ]
