# Generated by Django 5.2.7 on 2025-12-16 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0009_alter_wave_surveyyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Eindeutiger Survey-Name, z. B. 'SLC 2022'", max_length=200, unique=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, help_text='Optionales Jahr (z. B. 2022). Nicht zwingend eindeutig.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', 'name'],
            },
        ),
        migrations.AddField(
            model_name='wave',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waves', to='waves.survey'),
        ),
    ]
