# Generated by Django 5.2.7 on 2025-12-16 13:16

from django.db import migrations
import re

YEAR_RE = re.compile(r"(19|20)\d{2}")


def forwards(apps, schema_editor):
    Wave = apps.get_model("waves", "Wave")
    Survey = apps.get_model("waves", "Survey")

    values = (
        Wave.objects
        .exclude(surveyyear__isnull=True)
        .exclude(surveyyear__exact="")
        .values_list("surveyyear", flat=True)
        .distinct()
    )

    for survey_label in values:
        label = survey_label.strip()

        m = YEAR_RE.search(label)
        year = int(m.group(0)) if m else None

        name = f"EJ {year}" if year else label

        survey, _ = Survey.objects.get_or_create(
            name=name,
            defaults={"year": year},
        )

        if year and not survey.year:
            survey.year = year
            survey.save(update_fields=["year"])

        Wave.objects.filter(surveyyear=survey_label).update(survey=survey)


def backwards(apps, schema_editor):
    Wave = apps.get_model("waves", "Wave")
    Survey = apps.get_model("waves", "Survey")

    # Restore surveyyear (best-effort) and unlink waves
    for wave in Wave.objects.select_related("survey").all():
        if wave.survey:
            if wave.survey.year:
                wave.surveyyear = str(wave.survey.year)
            else:
                wave.surveyyear = wave.survey.name
            wave.survey = None
            wave.save(update_fields=["surveyyear", "survey"])

    # Remove surveys that are no longer referenced
    Survey.objects.filter(waves__isnull=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("waves", "0010_survey_wave_survey"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
