# Generated by Django 5.2.7 on 2025-12-16 13:16

from django.db import migrations

from django.db import migrations
import re


YEAR_RE = re.compile(r"(19|20)\d{2}")


def forwards(apps, schema_editor):
    Wave = apps.get_model("waves", "Wave")
    Survey = apps.get_model("waves", "Survey")

    # distinct surveyyear values from waves
    values = (
        Wave.objects
        .exclude(surveyyear__isnull=True)
        .exclude(surveyyear__exact="")
        .values_list("surveyyear", flat=True)
        .distinct()
    )

    for survey_label in values:
        name = survey_label.strip()

        # Try to extract a 4-digit year from the label (optional)
        m = YEAR_RE.search(name)
        year = int(m.group(0)) if m else None

        survey, _ = Survey.objects.get_or_create(
            name=name,
            defaults={"year": year},
        )

        # If survey exists but year is empty, fill it if we found one
        if year and not survey.year:
            survey.year = year
            survey.save(update_fields=["year"])

        # Assign all waves with that surveyyear to this survey
        Wave.objects.filter(surveyyear=survey_label, survey__isnull=True).update(survey=survey)


def backwards(apps, schema_editor):
    Wave = apps.get_model("waves", "Wave")
    Survey = apps.get_model("waves", "Survey")

    # Put the survey name back into wave.surveyyear if missing (defensive)
    for wave in Wave.objects.select_related("survey").all():
        if wave.survey and (not wave.surveyyear):
            wave.surveyyear = wave.survey.name
            wave.save(update_fields=["surveyyear"])

    # Optionally remove surveys that are no longer referenced
    Survey.objects.filter(waves__isnull=True).delete()




class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0010_survey_wave_survey'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
