# Generated by Django 5.2.7 on 2025-12-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0011_migrate_wave_surveyyear_to_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(help_text="Eindeutiger Survey-Name, z. B. 'EJ 2022'", max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optionales Jahr des Surveys', null=True),
        ),
    ]
