# Generated by Django 5.2.7 on 2025-12-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0012_alter_survey_name_alter_survey_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(help_text="Eindeutiger Name der Befragung, z. B. 'EJ 2022'", max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Jahr der Befragung', null=True),
        ),
        migrations.AlterField(
            model_name='wave',
            name='instrument',
            field=models.CharField(default='CAWI', max_length=10),
            preserve_default=False,
        ),
    ]
