# Generated by Django 5.2.7 on 2025-12-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0013_alter_survey_name_alter_survey_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wave',
            name='instrument',
            field=models.CharField(choices=[('CAWI', 'CAWI'), ('PAPI', 'PAPI')], max_length=10),
        ),
    ]
