# Generated by Django 5.2.7 on 2025-12-19 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0014_alter_wave_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wave',
            name='cycle',
            field=models.CharField(max_length=200, verbose_name='Befragtengruppe'),
        ),
        migrations.AlterField(
            model_name='wave',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Feldende'),
        ),
        migrations.AlterField(
            model_name='wave',
            name='instrument',
            field=models.CharField(choices=[('CAWI', 'CAWI'), ('PAPI', 'PAPI')], max_length=10, verbose_name='Erhebungsmodus'),
        ),
        migrations.AlterField(
            model_name='wave',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Feldstart'),
        ),
        migrations.AlterField(
            model_name='wave',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waves', to='waves.survey', verbose_name='Befragung'),
        ),
        migrations.AddConstraint(
            model_name='wave',
            constraint=models.UniqueConstraint(fields=('survey', 'cycle', 'instrument'), name='uniq_wave_cycle_instrument_per_survey'),
        ),
    ]
