# Generated by Django 5.2.7 on 2026-01-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0020_alter_question_question_type'),
        ('waves', '0015_alter_wave_cycle_alter_wave_end_date_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wavequestion',
            constraint=models.UniqueConstraint(fields=('wave', 'question'), name='uq_wavequestion_wave_question'),
        ),
    ]
