# Generated by Django 5.2.7 on 2026-01-19 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0016_wavequestion_uq_wavequestion_wave_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaveModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name des Moduls, z. B. 'Soziodemographie'.", max_length=200)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Reihenfolge des Moduls innerhalb der Befragung.')),
                ('wave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='waves.wave')),
            ],
            options={
                'verbose_name': 'Modul',
                'verbose_name_plural': 'Module',
                'ordering': ['wave', 'sort_order', 'id'],
                'indexes': [models.Index(fields=['wave', 'sort_order'], name='idx_wavemodule_wave_sort')],
                'constraints': [models.UniqueConstraint(fields=('wave', 'sort_order'), name='uq_wavemodule_wave_sortorder'), models.UniqueConstraint(fields=('wave', 'name'), name='uq_wavemodule_wave_name')],
            },
        ),
    ]
