# Generated by Django 5.2.7 on 2026-03-25 16:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0017_wavemodule'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaveDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Kurzer Anzeigename für das Dokument.', max_length=200, verbose_name='Titel')),
                ('pdf_file', models.FileField(upload_to='wave_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='PDF-Datei')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sortierung')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Hochgeladen am')),
                ('wave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='waves.wave', verbose_name='Wave')),
            ],
            options={
                'verbose_name': 'Wave-Dokument',
                'verbose_name_plural': 'Wave-Dokumente',
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
