# Generated by Django 5.2.7 on 2026-03-25 16:51

import django.core.files.storage
import django.core.validators
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0018_wavedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wavedocument',
            name='pdf_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/ohlendorf/Django/SLC/private_uploads/wave_documents')), upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='PDF-Datei'),
        ),
    ]
