# Generated by Django 5.2.7 on 2026-04-13 15:33

import django.core.validators
import waves.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waves', '0019_alter_wavedocument_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wavedocument',
            name='pdf_file',
            field=models.FileField(storage=waves.storage.WaveDocumentStorage(), upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='PDF-Datei'),
        ),
    ]
