# Generated by Django 5.2.6 on 2025-09-15 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questiontext', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WaveQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('wave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waves.wave')),
            ],
            options={
                'unique_together': {('wave', 'question')},
            },
        ),
        migrations.AddField(
            model_name='question',
            name='waves',
            field=models.ManyToManyField(related_name='questions', through='questions.WaveQuestion', to='waves.wave'),
        ),
    ]
