# Generated by Django 5.2.6 on 2025-09-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='legacy_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
