# Generated by Django 5.2.6 on 2025-09-30 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_legacy_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wavequestion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='wavequestion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='wavequestion',
            name='wave',
        ),
    ]
