# Generated by Django 5.2.6 on 2025-09-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_wavequestion_unique_together_and_more'),
        ('waves', '0003_wavequestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='waves',
            field=models.ManyToManyField(related_name='questions', through='waves.WaveQuestion', to='waves.wave'),
        ),
        migrations.DeleteModel(
            name='WaveQuestion',
        ),
    ]
