# Generated by Django 5.2.6 on 2025-10-09 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_keyword_question_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Construct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_1', models.CharField(blank=True, max_length=255, null=True)),
                ('level_2', models.CharField(blank=True, max_length=255, null=True)),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConstructPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('filepath', models.CharField(blank=True, max_length=500, null=True)),
                ('legacy_id', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='construct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='questions.construct'),
        ),
        migrations.AddField(
            model_name='construct',
            name='constructpaper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constructs', to='questions.constructpaper'),
        ),
    ]
