# Generated by Django 5.2.6 on 2025-10-10 11:46

import django.db.models.deletion
import questions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_construct_constructpaper_question_construct_and_more'),
        ('waves', '0003_wavequestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=questions.models.screenshot_upload_path)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='waves.wave')),
            ],
        ),
    ]
