# Generated by Django 5.2.6 on 2025-10-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_questionscreenshot'),
        ('waves', '0007_remove_wavequestion_unique_wave_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionscreenshot',
            name='wave',
        ),
        migrations.AddField(
            model_name='questionscreenshot',
            name='wavequestions',
            field=models.ManyToManyField(blank=True, related_name='screenshots', to='waves.wavequestion'),
        ),
    ]
