# Generated by Django 5.2.6 on 2025-10-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_remove_questionscreenshot_wave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionscreenshot',
            name='legacy_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
