# Generated by Django 5.2.7 on 2025-12-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_questions_fulltext_indices'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='instruction',
            field=models.TextField(blank=True, help_text='Instruktionstext (is).'),
        ),
        migrations.AddField(
            model_name='question',
            name='item_stem',
            field=models.TextField(blank=True, help_text="Itemstamm, z. B. 'Ich bin jemand, der…' (st)."),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(blank=True, choices=[('open', 'Offene Frage'), ('single_vertical', 'Einfachauswahl vertikal'), ('single_horizontal', 'Einfachauswahl horizontal'), ('multi_vertical', 'Mehrfachauswahl vertikal'), ('multi_horizontal', 'Mehrfachauswahl horizontal'), ('matrix_single', 'Einfachauswahl-Matrix'), ('matrix_multi', 'Mehrfachauswahl-Matrix'), ('semantic_diff', 'Semantisches Differenzial'), ('other', 'Sonstiger Fragetyp')], help_text='Fragetyp (qt).', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='questiontext',
            field=models.TextField(help_text='Fragetext (qt).'),
        ),
    ]
