# Generated by Django 5.2.7 on 2025-12-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_question_instruction_question_item_stem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_options',
            field=models.JSONField(blank=True, default=list, help_text="Antwortoptionen der Frage als Liste von Objekten, z.B. [{'uid': 'ao1', 'value': '1', 'label': 'sehr gut'}]."),
        ),
        migrations.AlterField(
            model_name='question',
            name='questiontext',
            field=models.TextField(help_text='Fragetext (q).'),
        ),
    ]
