# Generated by Django 5.2.7 on 2025-12-16 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_question_answer_options_alter_question_questiontext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionScreenshot',
        ),
    ]
