# Generated by Django 5.2.7 on 2025-12-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_delete_questionscreenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='questions', to='questions.keyword'),
        ),
        migrations.AlterField(
            model_name='question',
            name='questiontext',
            field=models.TextField(blank=True, help_text='Fragetext (q).'),
        ),
    ]
