# Generated by Django 5.2.7 on 2025-12-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_alter_question_keywords_alter_question_questiontext'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='missing_values',
            field=models.TextField(blank=True, help_text='Fehlende Werte (mv) im Format mv: Wert : anzuzeigender Wert : Wertelabel (z. B.  mv: -999 : : Das weiß ich nicht.).'),
        ),
        migrations.AddField(
            model_name='question',
            name='top_categories',
            field=models.TextField(blank=True, help_text='Gruppierung von Items/Antwortoptionen nach übergeordndeten Kategorien (ka)'),
        ),
    ]
