# Generated by Django 5.2.7 on 2025-12-27 13:21

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_question_missing_values_question_top_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='keyword',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_keyword_name_lower'),
        ),
    ]
