# Generated by Django 5.2.7 on 2025-12-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_alter_keyword_name_keyword_uniq_keyword_name_lower'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='items',
            field=models.JSONField(blank=True, default=list, help_text="Items der Frage als Liste von Objekten, z.B. [{'uid': 'it1', 'value': '1', 'label': 'stimme zu'}]."),
        ),
    ]
