# Generated by Django 5.2.7 on 2025-12-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0018_question_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type_other',
            field=models.CharField(blank=True, help_text="Freitext, falls 'Sonstiger Fragetyp'.", max_length=255),
        ),
    ]
