# Generated by Django 5.2.7 on 2026-01-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_question_question_type_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(blank=True, choices=[('open', 'Offene Frage'), ('single_vertical', 'Einfachauswahl vertikal'), ('single_horizontal', 'Einfachauswahl horizontal'), ('multi_vertical', 'Mehrfachauswahl vertikal'), ('multi_horizontal', 'Mehrfachauswahl horizontal'), ('matrix_single', 'Einfachauswahl-Matrix'), ('matrix_multi', 'Mehrfachauswahl-Matrix'), ('semantic_diff', 'Semantisches Differenzial'), ('other', 'Sonstiger Fragetyp / Mischtypen')], help_text='Fragetyp (qt).', max_length=50),
        ),
    ]
