# Generated by Django 5.2.7 on 2026-01-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0021_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(blank=True, choices=[('open', 'Offene Frage'), ('single_vertical', 'Einfachauswahl vertikal'), ('single_horizontal', 'Einfachauswahl horizontal'), ('single_dropdown', 'Einfachauswahl Dropdown'), ('multi_vertical', 'Mehrfachauswahl vertikal'), ('multi_horizontal', 'Mehrfachauswahl horizontal'), ('matrix_single_vertical', 'Einfachauswahl-Matrix vertikal'), ('matrix_single_horizontal', 'Einfachauswahl-Matrix horizontal'), ('matrix_multi', 'Mehrfachauswahl-Matrix'), ('semantic_diff', 'Semantisches Differenzial'), ('matrix_double', 'Doppel-Matrix'), ('datepicker', 'Datepicker'), ('other', 'Sonstiger Fragetyp / Mischtypen')], help_text='Fragetyp (qt).', max_length=50),
        ),
    ]
