# Generated by Django 5.2.7 on 2026-07-22 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0022_alter_question_question_type'),
        ('waves', '0020_alter_wavedocument_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionVersionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="Optionale Bezeichnung, z. B. 'Geschlecht'.", max_length=255, verbose_name='Interne Bezeichnung')),
                ('note', models.TextField(blank=True, help_text='Optionale interne Erläuterung zur Versionsgruppe.', verbose_name='Notiz')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
            ],
            options={
                'verbose_name': 'Fragen-Versionsgruppe',
                'verbose_name_plural': 'Fragen-Versionsgruppen',
                'ordering': ('name', 'id'),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='version_number',
            field=models.PositiveIntegerField(default=0, help_text='0 für die Ursprungsfassung, danach fortlaufend 1, 2, 3 …', verbose_name='Versionsnummer'),
        ),
        migrations.AddField(
            model_name='question',
            name='version_group',
            field=models.ForeignKey(blank=True, help_text='Nur setzen, wenn diese Frage zu einer Versionsfamilie gehört.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='questions.questionversiongroup', verbose_name='Versionsgruppe'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(condition=models.Q(('version_group__isnull', False)), fields=('version_group', 'version_number'), name='uniq_question_version_number_in_group'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('version_group__isnull', False), ('version_number', 0), _connector='OR'), name='question_without_group_has_version_zero'),
        ),
    ]
