# Generated by Django 5.2.7 on 2026-07-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0023_questionversiongroup_question_version_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionversiongroup',
            options={'ordering': ('name', 'id'), 'verbose_name': 'QuestionVersionGroup', 'verbose_name_plural': 'QuestionVersionGroups'},
        ),
        migrations.AddField(
            model_name='question',
            name='version_reason',
            field=models.TextField(blank=True, default='', help_text='Begründung für die Anlage dieser konkreten Fragenversion.', verbose_name='Versionierungsgrund'),
        ),
    ]
