# Generated by Django 5.2.7 on 2026-07-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0024_alter_questionversiongroup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='completion_time_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Bearbeitungszeit der Frage in Sekunden.', null=True, verbose_name='Bearbeitungszeit (Sekunden)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(blank=True, choices=[('open', 'Offene Frage'), ('single_vertical', 'Einfachauswahl vertikal'), ('single_horizontal', 'Einfachauswahl horizontal'), ('single_dropdown', 'Einfachauswahl Dropdown'), ('multi_vertical', 'Mehrfachauswahl vertikal'), ('multi_horizontal', 'Mehrfachauswahl horizontal'), ('matrix_single_vertical', 'Einfachauswahl-Matrix vertikal'), ('matrix_single_horizontal', 'Einfachauswahl-Matrix horizontal'), ('matrix_multi', 'Mehrfachauswahl-Matrix'), ('semantic_diff', 'Semantisches Differenzial'), ('matrix_double', 'Doppel-Matrix'), ('datepicker', 'Datepicker'), ('slider', 'Schieberegler'), ('other', 'Sonstiger Fragetyp / Mischtypen')], help_text='Fragetyp (qt).', max_length=50),
        ),
    ]
