# Generated by Django 5.2.7 on 2025-11-21 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0011_questions_fulltext_indices'),
        ('waves', '0008_wavequestion_legacy_screenshot_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WavePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagename', models.CharField(help_text="Interner Seitenname, z.B. 'dem123'.", max_length=200)),
                ('wave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='waves.wave')),
            ],
            options={
                'ordering': ['wave', 'pagename'],
                'unique_together': {('wave', 'pagename')},
            },
        ),
        migrations.CreateModel(
            name='WavePageScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(help_text='Pfad/Dateiname zum Screenshot (z.B. im media-Ordner).', max_length=500)),
                ('language', models.CharField(default='de', help_text="Sprache, z.B. 'de' oder 'en'.", max_length=5)),
                ('device', models.CharField(default='desktop', help_text="z.B. 'desktop' oder 'mobile'.", max_length=20)),
                ('wave_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='pages.wavepage')),
            ],
            options={
                'ordering': ['wave_page', 'language', 'device'],
            },
        ),
        migrations.CreateModel(
            name='WavePageQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_links', to='questions.question')),
                ('wave_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_questions', to='pages.wavepage')),
            ],
            options={
                'ordering': ['wave_page', 'question'],
                'unique_together': {('wave_page', 'question')},
            },
        ),
    ]
