# Generated by Django 5.2.7 on 2025-11-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
        ('waves', '0008_wavequestion_legacy_screenshot_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wavepage',
            options={'ordering': ['pagename']},
        ),
        migrations.AlterUniqueTogether(
            name='wavepage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='wavepage',
            name='waves',
            field=models.ManyToManyField(blank=True, help_text='Wellen, in denen diese Seite verwendet wird.', related_name='pages', to='waves.wave'),
        ),
        migrations.RemoveField(
            model_name='wavepage',
            name='wave',
        ),
    ]
