# Generated by Django 5.2.7 on 2025-11-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_wavepage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wavepage',
            name='import_page_id',
            field=models.IntegerField(blank=True, help_text='Eindeutige ID aus der Import-Tabelle.', null=True),
        ),
    ]
