# Generated by Django 5.2.7 on 2025-11-22 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_wavepage_import_page_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wavepage',
            name='import_page_id',
        ),
    ]
