# Generated by Django 5.2.7 on 2025-11-26 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_wavepage_import_page_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wavepage',
            options={'ordering': ['pagename'], 'verbose_name': 'page', 'verbose_name_plural': 'pages'},
        ),
        migrations.AlterModelOptions(
            name='wavepagequestion',
            options={'ordering': ['wave_page', 'question'], 'verbose_name': 'questions on page', 'verbose_name_plural': 'questions on page'},
        ),
        migrations.AlterModelOptions(
            name='wavepagescreenshot',
            options={'ordering': ['wave_page', 'language', 'device'], 'verbose_name': 'Screenshot (page)', 'verbose_name_plural': 'Screenshots (page)'},
        ),
    ]
