# Generated by Django 5.2.7 on 2025-12-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_wavepage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wavepage',
            name='introduction',
            field=models.TextField(blank=True, help_text='Einleitungstext auf Seitenebene (in).'),
        ),
        migrations.AddField(
            model_name='wavepage',
            name='page_heading',
            field=models.TextField(blank=True, help_text='Überschrift der Seite (hl).', max_length=255),
        ),
        migrations.AddField(
            model_name='wavepage',
            name='page_programming_notes',
            field=models.TextField(blank=True, help_text='Zusätzliche Hinweise zur Programmierung (hi).'),
        ),
        migrations.AddField(
            model_name='wavepage',
            name='transition_control',
            field=models.TextField(blank=True, help_text='Transitionskontrolle in Textform (tc).'),
        ),
        migrations.AddField(
            model_name='wavepage',
            name='transitions',
            field=models.TextField(blank=True, help_text='Filter (tr).'),
        ),
        migrations.AlterField(
            model_name='wavepage',
            name='pagename',
            field=models.CharField(help_text="Interner Seitenname, z.B. 'dem123' (pn).", max_length=200),
        ),
    ]
