# Generated by Django 5.2.7 on 2025-12-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_wavepage_introduction_wavepage_page_heading_and_more'),
        ('waves', '0015_alter_wave_cycle_alter_wave_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wavepage',
            name='pagename',
            field=models.CharField(help_text="Interner Seitenname, z.B. 'dem_123' (pn).", max_length=200),
        ),
        migrations.AlterField(
            model_name='wavepage',
            name='waves',
            field=models.ManyToManyField(blank=True, help_text='Befragtengruppen, die diese Seite sehen.', related_name='pages', to='waves.wave'),
        ),
    ]
