# Generated by Django 5.2.7 on 2025-12-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_wavepage_pagename_alter_wavepage_waves'),
    ]

    operations = [
        migrations.AddField(
            model_name='wavepage',
            name='answer_validations',
            field=models.TextField(blank=True, help_text='Antwortvalidierungen (av).'),
        ),
        migrations.AddField(
            model_name='wavepage',
            name='control_variables',
            field=models.TextField(blank=True, help_text='Steuerungsvariablen (sv).'),
        ),
        migrations.AddField(
            model_name='wavepage',
            name='correction_notes',
            field=models.TextField(blank=True, help_text='Korrekturhinweise (kh).'),
        ),
        migrations.AddField(
            model_name='wavepage',
            name='forcing_variables',
            field=models.TextField(blank=True, help_text='Forcierungsvariablen (fv).'),
        ),
        migrations.AddField(
            model_name='wavepage',
            name='formatting',
            field=models.TextField(blank=True, help_text='Formatierung (fo).'),
        ),
        migrations.AddField(
            model_name='wavepage',
            name='helper_variables',
            field=models.TextField(blank=True, help_text='Hilfsvariablen (hv).'),
        ),
        migrations.AddField(
            model_name='wavepage',
            name='visibility_conditions',
            field=models.TextField(blank=True, help_text='Einblendbedingungen (vc).'),
        ),
    ]
