# Generated by Django 5.2.7 on 2026-01-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_page_survey_integrity_triggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wavepage',
            name='transition_control',
            field=models.TextField(blank=True, help_text='Transitionskontrolle (tc).'),
        ),
    ]
