# Generated by Django 5.2.7 on 2026-01-18 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_wavepage_transition_control'),
        ('waves', '0016_wavequestion_uq_wavequestion_wave_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='WavePageWave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wave_links', to='pages.wavepage')),
                ('wave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_links', to='waves.wave')),
            ],
        ),
        migrations.AddField(
            model_name='wavepage',
            name='waves_new',
            field=models.ManyToManyField(blank=True, related_name='pages_new', through='pages.WavePageWave', to='waves.wave'),
        ),
        migrations.AddIndex(
            model_name='wavepagewave',
            index=models.Index(fields=['wave', 'sort_order'], name='idx_wavepagewave_wave_sort'),
        ),
        migrations.AddConstraint(
            model_name='wavepagewave',
            constraint=models.UniqueConstraint(fields=('wave', 'page'), name='uq_wavepagewave_wave_page'),
        ),
    ]
