# Generated by Django 5.2.7 on 2026-01-18 17:15
from collections import defaultdict
from django.db import migrations

OLD_M2M_TABLE = "pages_wavepage_waves"

def forwards(apps, schema_editor):
    WavePage = apps.get_model("pages", "WavePage")
    WavePageWave = apps.get_model("pages", "WavePageWave")

    if WavePageWave.objects.exists():
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"SELECT wavepage_id, wave_id FROM {OLD_M2M_TABLE}")
        rows = cursor.fetchall()

    wave_to_pages = defaultdict(list)
    for page_id, wave_id in rows:
        wave_to_pages[wave_id].append(page_id)

    to_create = []
    for wave_id, page_ids in wave_to_pages.items():
        pages = (
            WavePage.objects
            .filter(id__in=page_ids)
            .values("id", "pagename")
        )
        pages_sorted = sorted(pages, key=lambda d: ((d["pagename"] or "").lower(), d["id"]))
        for idx, p in enumerate(pages_sorted, start=1):
            to_create.append(WavePageWave(wave_id=wave_id, page_id=p["id"], sort_order=idx))

    if to_create:
        WavePageWave.objects.bulk_create(to_create, batch_size=2000)

def backwards(apps, schema_editor):
    WavePageWave = apps.get_model("pages", "WavePageWave")
    WavePageWave.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_wavepagewave_wavepage_waves_new_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
