# Generated by Django 5.2.7 on 2026-01-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_copy_waves_to_wavepagewave'),
        ('waves', '0016_wavequestion_uq_wavequestion_wave_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wavepage',
            name='waves_new',
        ),
        migrations.AlterField(
            model_name='wavepage',
            name='waves',
            field=models.ManyToManyField(blank=True, related_name='pages', through='pages.WavePageWave', to='waves.wave'),
        ),
    ]
