# Generated by Django 5.2.7 on 2026-01-19 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_remove_wavepage_waves_new_alter_wavepage_waves'),
        ('waves', '0017_wavemodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='wavepagewave',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_links', to='waves.wavemodule'),
        ),
        migrations.AlterField(
            model_name='wavepage',
            name='waves',
            field=models.ManyToManyField(blank=True, related_name='pages', through='pages.WavePageWave', to='waves.wave'),
        ),
    ]
