# Generated by Django 5.2.7 on 2026-03-25 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_wavepagewave_module_alter_wavepage_waves'),
    ]

    operations = [
        migrations.CreateModel(
            name='WavePageQml',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(help_text="Ursprünglicher Dateiname der importierten XML-Datei, z. B. 'dem_08.xml'.", max_length=255)),
                ('xml_uid', models.CharField(blank=True, help_text="UID aus der XML-Datei, z. B. aus <zofar:page uid='dem_08'>.", max_length=200)),
                ('xml_content', models.TextField(help_text='Gesamter importierter XML-/QML-Code der Seite.')),
                ('imported_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt des ersten Imports.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aktualisierung.')),
                ('wave_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qml_file', to='pages.wavepage')),
            ],
            options={
                'verbose_name': 'QML-Datei (page)',
                'verbose_name_plural': 'QML-Dateien (page)',
                'ordering': ['wave_page'],
            },
        ),
    ]
