# Generated by Django 5.2.7 on 2026-05-04 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_add_sort_order_to_wavepagequestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wavepagequestion',
            options={'ordering': ['wave_page', 'sort_order', 'id'], 'verbose_name': 'questions on page', 'verbose_name_plural': 'questions on page'},
        ),
    ]
