# Generated by Django 5.2.7 on 2026-09-08 15:05

from collections import defaultdict
from django.db import migrations, models


def forwards(apps, schema_editor):
    """
    Überträgt die bisher implizite Seiten-/Fragen-/Wave-Zuordnung
    in das neue explizite M2M-Feld WavePageQuestion.waves.

    Für jeden bestehenden WavePageQuestion-Link gilt:

        neue Waves
        =
        Waves der Seite
        ∩
        Waves der Frage

    Damit entspricht der Zustand nach der Migration exakt der bisherigen
    Interpretation der Daten.
    """

    WavePageQuestion = apps.get_model("pages", "WavePageQuestion")
    WavePageWave = apps.get_model("pages", "WavePageWave")
    WaveQuestion = apps.get_model("waves", "WaveQuestion")

    # Welche Waves gehören zu welcher Seite?
    page_waves = defaultdict(set)

    for page_id, wave_id in (
        WavePageWave.objects
        .values_list("page_id", "wave_id")
        .iterator()
    ):
        page_waves[page_id].add(wave_id)

    # In welchen Waves kommt welche Frage grundsätzlich vor?
    question_waves = defaultdict(set)

    for question_id, wave_id in (
        WaveQuestion.objects
        .values_list("question_id", "wave_id")
        .iterator()
    ):
        question_waves[question_id].add(wave_id)

    # Implizites Through-Modell des neuen M2M-Feldes.
    through_model = (
        WavePageQuestion
        ._meta
        .get_field("waves")
        .remote_field
        .through
    )

    to_create = []

    for wpq_id, page_id, question_id in (
        WavePageQuestion.objects
        .values_list(
            "id",
            "wave_page_id",
            "question_id",
        )
        .iterator()
    ):
        matching_wave_ids = (
            page_waves.get(page_id, set())
            & question_waves.get(question_id, set())
        )

        for wave_id in matching_wave_ids:
            to_create.append(
                through_model(
                    wavepagequestion_id=wpq_id,
                    wave_id=wave_id,
                )
            )

        # Nicht unnötig alles gleichzeitig im Speicher halten.
        if len(to_create) >= 2000:
            through_model.objects.bulk_create(
                to_create,
                batch_size=2000,
                ignore_conflicts=True,
            )
            to_create.clear()

    if to_create:
        through_model.objects.bulk_create(
            to_create,
            batch_size=2000,
            ignore_conflicts=True,
        )


def backwards(apps, schema_editor):
    """
    Beim Zurückrollen werden nur die neu erzeugten M2M-Zuordnungen entfernt.
    Die bisherigen WavePageQuestion-, WavePageWave- und WaveQuestion-Daten
    bleiben unverändert erhalten.
    """

    WavePageQuestion = apps.get_model("pages", "WavePageQuestion")

    through_model = (
        WavePageQuestion
        ._meta
        .get_field("waves")
        .remote_field
        .through
    )

    through_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_alter_wavepagequestion_options'),
        ('waves', '0020_alter_wavedocument_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='wavepagequestion',
            name='waves',
            field=models.ManyToManyField(blank=True, related_name='page_question_links', to='waves.wave'),
        ),
        migrations.RunPython(
            forwards,
            backwards,
        ),
    ]
