# Generated by Django 5.2.6 on 2025-09-17 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_slcuser_delete_dbuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SLCUser',
        ),
    ]
