# Generated by Django 5.2.7 on 2025-12-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_delete_slcuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLCSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_edit_slc', 'Can edit SLC database')],
                'managed': True,
                'default_permissions': (),
            },
        ),
    ]
