# Generated by Django 5.2.6 on 2025-10-13 13:55

import variables.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('vallabname', models.CharField(max_length=255, unique=True)),
                ('values', models.JSONField(default=list, help_text='Liste von Objekten mit Schlüsseln value (int), order (int), text (str).', validators=[variables.models.validate_vallab_values])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('vallabname',),
            },
        ),
    ]
