# Generated by Django 5.2.6 on 2025-10-14 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_questionscreenshot_legacy_id'),
        ('variables', '0001_initial'),
        ('waves', '0008_wavequestion_legacy_screenshot_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('varname', models.CharField(max_length=50, unique=True)),
                ('varlab', models.CharField(max_length=255, unique=True, verbose_name='Variablenblabel')),
                ('ver', models.BooleanField(default=False, verbose_name='versioniert')),
                ('gen', models.BooleanField(default=False, verbose_name='generiert')),
                ('plausi', models.BooleanField(default=False, verbose_name='plausibilisiert')),
                ('flag', models.BooleanField(default=False, verbose_name='flag')),
                ('reason_ver', models.TextField(blank=True, null=True, verbose_name='Grund (versioniert)')),
                ('reason_gen', models.TextField(blank=True, null=True, verbose_name='Grund (generiert)')),
                ('reason_plausi', models.TextField(blank=True, null=True, verbose_name='Grund (plausibilisiert)')),
                ('reason_flag', models.TextField(blank=True, null=True, verbose_name='Grund (flag)')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='questions.question')),
                ('vallab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variables', to='variables.vallab')),
                ('waves', models.ManyToManyField(related_name='variables', to='waves.wave')),
            ],
            options={
                'verbose_name': 'Variable',
                'verbose_name_plural': 'Variablen',
                'ordering': ['varname'],
            },
        ),
    ]
