# Generated by Django 5.2.6 on 2025-10-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0002_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='varlab',
            field=models.CharField(max_length=255, verbose_name='Variablenblabel'),
        ),
    ]
