# Generated by Django 5.2.7 on 2026-01-02 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_delete_questionscreenshot'),
        ('variables', '0005_vars_fulltext_indices'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionvariable_links', to='questions.question')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionvariable_links', to='variables.variable')),
            ],
        ),
        migrations.AddField(
            model_name='variable',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='variables_m2m', through='variables.QuestionVariable', to='questions.question'),
        ),
        migrations.AddConstraint(
            model_name='questionvariable',
            constraint=models.UniqueConstraint(fields=('question', 'variable'), name='uq_question_variable'),
        ),
    ]
