# Generated by Django 5.2.7 on 2026-01-02 12:26

from django.db import migrations


def forwards(apps, schema_editor):
    Variable = apps.get_model("variables", "Variable")
    QuestionVariable = apps.get_model("variables", "QuestionVariable")

    # bulk insert ohne Duplikate
    to_create = []
    existing = set(
        QuestionVariable.objects.values_list("question_id", "variable_id")
    )

    qs = Variable.objects.exclude(question_id__isnull=True).values_list("id", "question_id")
    for var_id, q_id in qs:
        key = (q_id, var_id)
        if key not in existing:
            to_create.append(QuestionVariable(question_id=q_id, variable_id=var_id))

    if to_create:
        QuestionVariable.objects.bulk_create(to_create, ignore_conflicts=True)


def backwards(apps, schema_editor):
    # Rückwärts: löscht die Links, setzt aber FK nicht zurück (den FK gibts noch in dieser Phase)
    QuestionVariable = apps.get_model("variables", "QuestionVariable")
    QuestionVariable.objects.all().delete()




class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0006_questionvariable_variable_questions_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
