# Generated by Django 5.2.7 on 2026-01-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_delete_questionscreenshot'),
        ('variables', '0007_copy_variable_fk_to_m2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='question',
        ),
        migrations.AlterField(
            model_name='variable',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='variables', through='variables.QuestionVariable', to='questions.question'),
        ),
    ]
