# Generated by Django 5.2.7 on 2026-01-02 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_delete_questionscreenshot'),
        ('variables', '0008_remove_variable_question_alter_variable_questions'),
        ('waves', '0012_alter_survey_name_alter_survey_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionVariableWave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_variable_wave_links', to='questions.question')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_variable_wave_links', to='variables.variable')),
                ('wave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_variable_wave_links', to='waves.wave')),
            ],
            options={
                'indexes': [models.Index(fields=['question', 'wave'], name='idx_qvw_question_wave'), models.Index(fields=['variable', 'wave'], name='idx_qvw_variable_wave')],
                'constraints': [models.UniqueConstraint(fields=('question', 'variable', 'wave'), name='uq_question_variable_wave')],
            },
        ),
    ]
