# Generated by Django 5.2.7 on 2026-01-02 15:48

from django.db import migrations


def forwards(apps, schema_editor):
    Variable = apps.get_model("variables", "Variable")
    QuestionVariable = apps.get_model("variables", "QuestionVariable")
    QuestionVariableWave = apps.get_model("variables", "QuestionVariableWave")

    # Auto-through model für Variable.waves (wavevar)
    WavesThrough = Variable._meta.get_field("waves").remote_field.through

    # Map: variable_id -> [question_id, ...]
    var_to_qids = {}
    for var_id, q_id in QuestionVariable.objects.values_list("variable_id", "question_id"):
        var_to_qids.setdefault(var_id, []).append(q_id)

    if not var_to_qids:
        return  # nichts zu migrieren

    # Map: variable_id -> [wave_id, ...]
    var_to_wids = {}
    for var_id, w_id in WavesThrough.objects.values_list("variable_id", "wave_id"):
        # Wir sammeln auch Waves für technische Variablen, die werden später einfach ignoriert,
        # weil sie nicht in var_to_qids vorkommen.
        var_to_wids.setdefault(var_id, []).append(w_id)

    # Triad-Links erzeugen
    to_create = []
    BATCH = 5000

    for var_id, q_ids in var_to_qids.items():
        w_ids = var_to_wids.get(var_id)
        if not w_ids:
            continue  # Variable hat (noch) keine waves, dann keine Triad-Links

        # (q,v,w) für alle Kombinationen
        for q_id in q_ids:
            for w_id in w_ids:
                to_create.append(
                    QuestionVariableWave(question_id=q_id, variable_id=var_id, wave_id=w_id)
                )

        if len(to_create) >= BATCH:
            QuestionVariableWave.objects.bulk_create(to_create, ignore_conflicts=True)
            to_create.clear()

    if to_create:
        QuestionVariableWave.objects.bulk_create(to_create, ignore_conflicts=True)


def backwards(apps, schema_editor):
    # Konservativ: Triad-Tabelle leeren (für Rollback im Branch).
    QuestionVariableWave = apps.get_model("variables", "QuestionVariableWave")
    QuestionVariableWave.objects.all().delete()



class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0009_questionvariablewave'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
