# Generated by Django 5.2.7 on 2026-01-02 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0010_migrate_qvw_from_wavevar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='questions',
        ),
        migrations.DeleteModel(
            name='QuestionVariable',
        ),
    ]
