# Generated by Django 5.2.7 on 2026-01-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0011_remove_variable_questions_delete_questionvariable'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='is_technical',
            field=models.BooleanField(default=False, verbose_name='technische Variable'),
        ),
    ]
