# Generated by Django 5.2.7 on 2026-01-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0012_variable_is_technical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='varlab',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Variablenblabel'),
        ),
    ]
